# Generated by Django 4.2.6 on 2023-10-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.TextField(default='', max_length=20, verbose_name='student')),
                ('grade', models.CharField(choices=[('1° B', '1° Básico'), ('2° B', '2° Básico'), ('3° B', '3° Básico'), ('4° B', '4° Básico'), ('4° B', '5° Básico'), ('6° B', '6° Básico'), ('7° B', '7° Básico'), ('8° B', '8° Básico'), ('1° M', '1° Medio'), ('2° M', '2° Medio'), ('3° M', '3° Medio'), ('4° M', '4° Medio'), ('Docente', 'Docente')], default=None, max_length=8)),
                ('score', models.IntegerField(default=0, verbose_name='student score')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='upload date and time')),
            ],
        ),
    ]
