# Generated by Django 4.2.6 on 2023-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingentry',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='rankingentry',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='rankingentry',
            name='student',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre Estudiante:'),
        ),
    ]
