# Generated by Django 4.2.6 on 2023-10-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rankingentry_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingentry',
            name='grade',
            field=models.CharField(choices=[('1° B', '1° Básico'), ('2° B', '2° Básico'), ('3° B', '3° Básico'), ('4° B', '4° Básico'), ('4° B', '5° Básico'), ('6° B', '6° Básico'), ('7° B', '7° Básico'), ('8° B', '8° Básico'), ('1° M', '1° Medio'), ('2° M', '2° Medio'), ('3° M', '3° Medio'), ('4° M', '4° Medio'), ('Docente', 'Docente')], default=None, max_length=8, verbose_name='Curso'),
        ),
    ]
